services:
  proxy:
    extends:
      file: docker-compose.yaml
      service: proxy
  inference-0:
    extends:
      file: docker-compose.yaml
      service: inference-0
    # these lines are needed for CUDA acceleration
    # devices:
    #   - nvidia.com/gpu=all
  server:
    extends:
      file: docker-compose.yaml
      service: server
    image: logdetective/server
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
  packit-interface:
    extends:
      file: docker-compose.yaml
      service: packit-interface

volumes:
  database_data:
    driver: local
