"""Add discussion missing

Revision ID: 00e7e0a8a20c
Revises: dda93a488cbf
Create Date: 2025-07-28 14:06:11.692649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "00e7e0a8a20c"
down_revision: Union[str, None] = "dda93a488cbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column(
            "discussion_missing",
            sa.Boolean(),
            nullable=False,
            comment="Parent discussion missing",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "discussion_missing")
    # ### end Alembic commands ###
