"""Create general task queue

Revision ID: 187d87e40161
Revises: 9fe3d0544cba
Create Date: 2026-09-08 08:41:58.185752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "187d87e40161"
down_revision: Union[str, None] = "9fe3d0544cba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "task_id", sa.UUID(), nullable=False, comment="Task ID as UUID-4 string"
        ),
        sa.Column(
            "request_received_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the request was received",
        ),
        sa.Column(
            "response_returned_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the analysis result was returned to caller",
        ),
        sa.Column(
            "response_metrics_id",
            sa.Integer(),
            nullable=True,
            comment="The id of the analyze_request_metrics record for this task",
        ),
        sa.Column(
            "state",
            sa.Enum("scheduled", "done", "in_progress", "error", name="analysisstate"),
            nullable=False,
            comment="State of the analysis task",
        ),
        sa.Column(
            "attempt_count",
            sa.Integer(),
            nullable=False,
            comment="Number of attempts made to finish analysis",
        ),
        sa.Column(
            "task_metadata",
            sa.JSON(),
            nullable=True,
            comment="Additional information supplied with the task",
        ),
        sa.Column(
            "response",
            sa.LargeBinary(length=314572800),
            nullable=True,
            comment="Given response (with explanation and snippets) saved in a zip format",
        ),
        sa.Column(
            "task_type",
            sa.Enum("generic", "koji", name="tasktype"),
            nullable=False,
            comment="Type of the task being processed",
        ),
        sa.Column(
            "external_task_id",
            sa.String(),
            nullable=True,
            comment="Task ID supplied by external system",
        ),
        sa.ForeignKeyConstraint(
            ["response_metrics_id"],
            ["analyze_request_metrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_analysis_external_task_id"),
        "task_analysis",
        ["external_task_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_task_analysis_request_received_at"),
        "task_analysis",
        ["request_received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_analysis_response_returned_at"),
        "task_analysis",
        ["response_returned_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_analysis_state"), "task_analysis", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_task_analysis_task_id"), "task_analysis", ["task_id"], unique=True
    )
    op.drop_index(
        op.f("ix_koji_task_analysis_koji_instance"), table_name="koji_task_analysis"
    )
    op.drop_index(
        op.f("ix_koji_task_analysis_log_file_name"), table_name="koji_task_analysis"
    )
    op.drop_index(
        op.f("ix_koji_task_analysis_request_received_at"),
        table_name="koji_task_analysis",
    )
    op.drop_index(
        op.f("ix_koji_task_analysis_task_id"), table_name="koji_task_analysis"
    )
    op.drop_table("koji_task_analysis")
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "analysis_completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the analysis was completed",
        ),
    )
    op.create_index(
        op.f("ix_analyze_request_metrics_analysis_completed_at"),
        "analyze_request_metrics",
        ["analysis_completed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analyze_request_metrics_analysis_completed_at"),
        table_name="analyze_request_metrics",
    )
    op.drop_column("analyze_request_metrics", "analysis_completed_at")
    op.create_table(
        "koji_task_analysis",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "koji_instance", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("task_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "log_file_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "request_received_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Timestamp when the request was received",
        ),
        sa.Column(
            "response_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="The id of the analyze request metrics for this task",
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["analyze_request_metrics.id"],
            name=op.f("koji_task_analysis_response_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("koji_task_analysis_pkey")),
    )
    op.create_index(
        op.f("ix_koji_task_analysis_task_id"),
        "koji_task_analysis",
        ["task_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_koji_task_analysis_request_received_at"),
        "koji_task_analysis",
        ["request_received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_koji_task_analysis_log_file_name"),
        "koji_task_analysis",
        ["log_file_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_koji_task_analysis_koji_instance"),
        "koji_task_analysis",
        ["koji_instance"],
        unique=False,
    )
    op.drop_index(op.f("ix_task_analysis_task_id"), table_name="task_analysis")
    op.drop_index(op.f("ix_task_analysis_state"), table_name="task_analysis")
    op.drop_index(
        op.f("ix_task_analysis_response_returned_at"), table_name="task_analysis"
    )
    op.drop_index(
        op.f("ix_task_analysis_request_received_at"), table_name="task_analysis"
    )
    op.drop_index(op.f("ix_task_analysis_external_task_id"), table_name="task_analysis")
    op.drop_table("task_analysis")
    # ### end Alembic commands ###
