"""Add gitlab metric detection

Revision ID: 2f60bb92411f
Revises: bbc5b9c1f0b3
Create Date: 2025-04-23 16:42:04.385783

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2f60bb92411f"
down_revision: Union[str, None] = "bbc5b9c1f0b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE endpointtype ADD VALUE 'ANALYZE_GITLAB_JOB';")
    op.execute("COMMIT;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE endpointtype DROP VALUE 'ANALYZE_GITLAB_JOB';")
    op.execute("COMMIT;")
    # ### end Alembic commands ###
