"""Save compressed response in metrics table

Revision ID: 360aea89443f
Revises: d90c3ebde7ed
Create Date: 2025-04-30 09:20:43.175618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "360aea89443f"
down_revision: Union[str, None] = "d90c3ebde7ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "compressed_response",
            sa.LargeBinary(length=314572800),
            nullable=True,
            comment="Given response (with explanation and snippets) saved in a zip format",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyze_request_metrics", "compressed_response")
    # ### end Alembic commands ###
