"""Add tables for annotated builds

Revision ID: 60e342e6c0f5
Revises: 725400e0ffb4
Create Date: 2026-06-10 09:04:16.984579

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60e342e6c0f5"
down_revision: Union[str, None] = "725400e0ffb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotated_builds",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "problem", sa.String(), nullable=False, comment="Full problem description"
        ),
        sa.Column(
            "solution",
            sa.String(),
            nullable=False,
            comment="Full solution to the issue.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotated_artifacts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "annotated_build_id",
            sa.BigInteger(),
            nullable=False,
            comment="Source build of the artifact",
        ),
        sa.ForeignKeyConstraint(
            ["annotated_build_id"],
            ["annotated_builds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotated_artifacts_annotated_build_id"),
        "annotated_artifacts",
        ["annotated_build_id"],
        unique=False,
    )
    op.create_table(
        "annotated_snippets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("annotation", sa.String(), nullable=False),
        # Change vector size depending on the model used
        sa.Column("text_embedding", VECTOR(dim=384), nullable=False),
        sa.Column(
            "source_artifact_id",
            sa.BigInteger(),
            nullable=False,
            comment="Source artifact of the annotated snippet",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["annotated_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotated_snippets_source_artifact_id"),
        "annotated_snippets",
        ["source_artifact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_annotated_snippets_text_embedding"),
        "annotated_snippets",
        ["text_embedding"],
        unique=False,
        postgresql_with={  # Defaults from pgvector docs
            "m": 16,  # Number of connections to neighbors
            "ef_construction": 64  # Closest neighbors to keep during build
        },
        postgresql_using="hnsw",  # Search algorithm
        postgresql_ops={
            "text_embedding": "vector_l2_ops"
        }
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_annotated_snippets_source_artifact_id"),
        table_name="annotated_snippets",
    )
    op.drop_index(
        op.f("ix_annotated_snippets_text_embedding"), table_name="annotated_snippets"
    )
    op.drop_table("annotated_snippets")
    op.drop_index(
        op.f("ix_annotated_artifacts_annotated_build_id"),
        table_name="annotated_artifacts",
    )
    op.drop_table("annotated_artifacts")
    op.drop_table("annotated_builds")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION vector")
