"""track_api_token_usage

Revision ID: 8887255bee62
Revises: a36b85ba4306
Create Date: 2026-09-10 12:17:00.134498

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8887255bee62"
down_revision: Union[str, None] = "a36b85ba4306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "api_token_name",
            sa.String(),
            nullable=True,
            comment="Non-secret name of the API token used for the request",
        ),
    )
    op.create_index(
        op.f("ix_analyze_request_metrics_api_token_name"),
        "analyze_request_metrics",
        ["api_token_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analyze_request_metrics_api_token_name"),
        table_name="analyze_request_metrics",
    )
    op.drop_column("analyze_request_metrics", "api_token_name")
    # ### end Alembic commands ###
