"""Remove reactions

Revision ID: 9fe3d0544cba
Revises: b266cb6cf7d5
Create Date: 2026-09-03 13:50:30.166364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9fe3d0544cba"
down_revision: Union[str, None] = "b266cb6cf7d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reactions_comment_id"), table_name="reactions")
    op.drop_table("reactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reactions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "comment_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="The associated comment (db) id",
        ),
        sa.Column(
            "reaction_type",
            sa.VARCHAR(length=127),
            autoincrement=False,
            nullable=False,
            comment="The type of reaction",
        ),
        sa.Column(
            "count",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="The number of reactions, of this type, given in the comment",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["comments.id"], name=op.f("reactions_comment_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reactions_pkey")),
        sa.UniqueConstraint(
            "comment_id",
            "reaction_type",
            name=op.f("uix_comment_reaction"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_reactions_comment_id"), "reactions", ["comment_id"], unique=False
    )
    # ### end Alembic commands ###
