"""Drop compressed_response column

Revision ID: a36b85ba4306
Revises: 187d87e40161
Create Date: 2026-09-08 09:41:31.731972

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a36b85ba4306"
down_revision: Union[str, None] = "187d87e40161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyze_request_metrics", "compressed_response")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "compressed_response",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=True,
            comment="Given response (with explanation and snippets) saved in a zip format",
        ),
    )
    # ### end Alembic commands ###
