"""Remove build_log and add mr relationship

Revision ID: af6742665052
Revises: 6e1fe3f1eccf
Create Date: 2025-04-11 10:56:58.532824

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "af6742665052"
down_revision: Union[str, None] = "6e1fe3f1eccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "merge_request_id",
            sa.Integer(),
            nullable=True,
            comment="Is this an analyze request coming from a merge request?",
        ),
    )
    op.create_foreign_key(
        None, "analyze_request_metrics", "merge_requests", ["merge_request_id"], ["id"]
    )
    op.drop_column("analyze_request_metrics", "log_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "log_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Log url for which analysis was requested",
        ),
    )
    op.drop_constraint(None, "analyze_request_metrics", type_="foreignkey")
    op.drop_column("analyze_request_metrics", "merge_request_id")
    # ### end Alembic commands ###
