"""Add Annotation Updates and source_path to Annotation Builds

Revision ID: b266cb6cf7d5
Revises: 60e342e6c0f5
Create Date: 2026-07-24 12:42:20.737766

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b266cb6cf7d5'
down_revision: Union[str, None] = '60e342e6c0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'annotation_updates',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('file_count', sa.Integer(), nullable=False),
        sa.Column('archive_date', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column(
        'annotated_builds',
        sa.Column(
            'source_path',
            sa.String(),
            nullable=False,
            comment='Path to the contribution in the archive'
        ),
    )
    op.create_unique_constraint(
        'uix_annotated_builds_source_path',
        'annotated_builds',
        ['source_path'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_annotated_builds_source_path', 'annotated_builds', type_='unique')
    op.drop_column('annotated_builds', 'source_path')
    op.drop_table('annotation_updates')
    # ### end Alembic commands ###
