"""Removed the compressed_log column

Revision ID: b4ed423319f9
Revises: 951aa61d8b86
Create Date: 2026-03-10 09:54:19.601119

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b4ed423319f9'
down_revision: Union[str, None] = '951aa61d8b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("analyze_request_metrics", "compressed_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "compressed_log",
            sa.LargeBinary(length=314572800),
            nullable=True,
            comment="Given response (with explanation and snippets) saved in a zip format",
        ),
    )
    # ### end Alembic commands ###
