"""Save compressed log in metrics table

Revision ID: d90c3ebde7ed
Revises: 2f60bb92411f
Create Date: 2025-04-29 07:19:29.695112

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d90c3ebde7ed"
down_revision: Union[str, None] = "2f60bb92411f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "compressed_log",
            sa.LargeBinary(length=314572800),
            nullable=False,
            comment="Log processed, saved in a zip format",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyze_request_metrics", "compressed_log")
    # ### end Alembic commands ###
