"""Verifying koji constraints

Revision ID: dda93a488cbf
Revises: ae776dc8160b
Create Date: 2025-07-17 11:05:38.135660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dda93a488cbf"
down_revision: Union[str, None] = "ae776dc8160b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "koji_task_analysis",
        "koji_instance",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="The koji instance identifier",
        existing_nullable=False,
    )
    op.alter_column(
        "koji_task_analysis",
        "task_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="The koji task ID",
        existing_nullable=False,
    )
    op.alter_column(
        "koji_task_analysis",
        "log_file_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="The name of the log file",
        existing_nullable=False,
    )
    op.drop_constraint("uix_task_id", "koji_task_analysis", type_="unique")
    op.create_index(
        op.f("ix_koji_task_analysis_log_file_name"),
        "koji_task_analysis",
        ["log_file_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_koji_task_analysis_log_file_name"), table_name="koji_task_analysis"
    )
    op.create_unique_constraint(
        "uix_task_id",
        "koji_task_analysis",
        ["task_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "koji_task_analysis",
        "log_file_name",
        existing_type=sa.VARCHAR(length=255),
        comment="The name of the log file",
        existing_nullable=False,
    )
    op.alter_column(
        "koji_task_analysis",
        "task_id",
        existing_type=sa.BIGINT(),
        comment="The koji task ID",
        existing_nullable=False,
    )
    op.alter_column(
        "koji_task_analysis",
        "koji_instance",
        existing_type=sa.VARCHAR(length=255),
        comment="The koji instance identifier",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
