"""Save compressed log in metrics table

Revision ID: fb7b51893c82
Revises: e73338ea1b53
Create Date: 2025-04-18 13:05:25.387000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fb7b51893c82"
down_revision: Union[str, None] = "e73338ea1b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyze_request_metrics",
        sa.Column(
            "zip_log",
            sa.LargeBinary(length=10485760),
            nullable=False,
            comment="Log processed, saved in a zip format",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyze_request_metrics", "zip_log")
    # ### end Alembic commands ###
