log:
  level: "INFO"
  path: "log/logdetective.log"
inference:
  max_tokens: -1
  log_probs: 1
extractor:
  context: true
  max_clusters: 16
  verbose: false
gitlab:
  url: https://gitlab.com
  api_token: glpat-XXXXXX
  max_artifact_size: 300
general:
  packages:
    - osci-internal-test-package
