inference:
  max_tokens: -1
  log_probs: 1
extractor:
  context: true
  max_clusters: 32
  verbose: false
gitlab:
  url: https://gitlab.com
  api_token: glpat-XXXXXX
general:
  packages:
    - osci-internal-test-package
