log:
  level_stream: "INFO"
  level_file: "DEBUG"
  path: "log/logdetective.log"
inference:
  max_tokens: 10000 # maximum number of tokens must be a positive integer
  log_probs: true
  url: http://inference-server:8000/v1
  api_token: "XXX" # Must not be empty, even if the server doesn't require authentication
  requests_per_minute: 6000
  http_timeout: 5.0
  http_connect_timeout: 3.07
  llm_api_timeout: 15.0 # Timeout for the LLM API client, how long should it wait for inference server response
  model: "fedora-copr/granite-4.0-h-tiny-quantized.w8a8"
  # Roles are used to format prompts into chat messages
  # If the roles are same, the system prompt and user message are concatenated
  user_role: user
  system_role: system
  # Limits on connections for AsyncOpenAI client
  max_concurrent_requests: 100
  max_keep_alive_connections: 20
# Separate LLM endpoint for snippet analysis, optional
# snippet_inference:
#   max_tokens: -1
#   log_probs: true
#   url: http://inference-server:8000
#   api_token: ""
#   requests_per_minute: 6
extractor:
  max_clusters: 25
  verbose: false
# Set this value to reasonable number based on maximum context length of your model
  # max_snippet_len: 2000
# Configuration for gitlab and koji
# gitlab:
#   "GitLab SaaS":
#     url: https://gitlab.com
#     api_token: glpat-XXXXXX
#     webhook_secrets: []
#     max_artifact_size: 300
#     timeout: 5.0
#   "GitLab Internal":
#     url: https://gitlab.example.com
#     api_token: glpat-XXXXXX
#     max_artifact_size: 300
#     webhook_secrets:
#       - example_secret
#     timeout: 6.0
# koji:
#   analysis_timeout: 15
#   max_artifact_size: 300

#   # Koji instances
#   instances:
#     "fedora":
#       xmlrpc_url: https://koji.fedoraproject.org/kojihub
#       tokens:
#         - example_token
general:
  max_artifact_size: 300  # in MiB
  devmode: False
  packages:
    - .*
  excluded_packages:
    - ^redhat-internal-.*
  # If set to value greater than zero, this option enables
  # filtering of snippets based on their estimated relevance.
  # Values equal, or higher, than number of snippets produced,
  # will effectivelly result in no filtering at all.
  # top_k_snippets: 0
  # Certainty ratings are disabled by default.
  # report_certainty: false
  # Log Detective server blocks analysis of local files
  # as a security measure. This block can be disabled.
  # block_localhost_urls: true
  # This is the period in seconds of how often is the emoji feedback collected,
  # default = 1 hour. Emoji feedback is collected only if `gitlab` config
  # contains some valid configuration entry.
  # collect_emojis_interval: 3600
