log:
  level_stream: "INFO"
  level_file: "DEBUG"
  path: "log/logdetective.log"
inference:
  max_tokens: 10000 # maximum number of tokens must be a positive integer
  log_probs: true
  url: http://inference-server:8000/v1
  api_token: "XXX" # Must not be empty, even if the server doesn't require authentication
  model: "fedora-copr/granite-4.0-h-tiny-quantized.w8a8"
  # Role needs to be aligned with chat template
  system_role: system
  # How many attempts agent has to make a correct tool call
  # increase when working with smaller models
  total_max_retries: 10
  max_retries_per_step: 3
extractor:
  max_clusters: 25
  verbose: false
# Set this value to reasonable number based on maximum context length of your model
  # max_snippet_len: 2000
# Configuration for gitlab and koji
# gitlab:
#   "GitLab SaaS":
#     url: https://gitlab.com
#     api_token: glpat-XXXXXX
#     webhook_secrets: []
#     max_artifact_size: 50
#     timeout: 5.0
#   "GitLab Internal":
#     url: https://gitlab.example.com
#     api_token: glpat-XXXXXX
#     max_artifact_size: 50
#     webhook_secrets:
#       - example_secret
#     timeout: 6.0
# koji:
#   analysis_timeout: 15
#   max_artifact_size: 50

#   # Koji instances
#   instances:
#     "fedora":
#       xmlrpc_url: https://koji.fedoraproject.org/kojihub
#       tokens:
#         - example_token
general:
  max_artifact_size: 50  # in MiB
  packages:
    - .*
  excluded_packages:
    - ^redhat-internal-.*
  # Log Detective server blocks analysis of local files
  # as a security measure. This block can be disabled.
  # block_localhost_urls: true
  # This is the period in seconds of how often is the emoji feedback collected,
  # default = 1 hour. Emoji feedback is collected only if `gitlab` config
  # contains some valid configuration entry.
  # collect_emojis_interval: 3600
