---
- name: "Start new EC2 machine"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "create a new training machine for logdetective"
      amazon.aws.ec2_instance:
        name: "{{ aws_new_instance.name }}"
        state: running
        profile: "{{ aws_new_instance.profile }}"
        region: "{{ aws_new_instance.region }}"
        key_name: "{{ aws_new_instance.ssh_key }}"
        count: 1
        image_id: "{{ aws_new_instance.image }}"
        instance_type: "{{ aws_new_instance.instance_type }}"
        detailed_monitoring: true

        # Use either network or vpc_subnet_id + security_group
        network:
          interfaces:
            - "{{ aws_new_instance.eni }}"
        # vpc_subnet_id: "{{ aws_new_instance.infra_subnet }}"
        # security_group: "{{ aws_new_instance.security_group }}"

        termination_protection: false
        wait: true
        tags:
          FedoraGroup: logdetective
        volumes:
          - ebs:
              volume_size: "{{ aws_new_instance.root_volume_size }}"
              encrypted: true
              delete_on_termination: true
            device_name: /dev/sda1
      register: instances_started

    - name: associate the elastic IP with the new eni
      community.aws.ec2_eip:
        device_id: "{{ instances_started.instances[0].network_interfaces[0].network_interface_id }}"
        ip: "{{ aws_new_instance.elastic_ip }}"
        in_vpc: true
        region: "{{ aws_new_instance.region }}"
        state: present
      when:
        - aws_new_instance.eni is not defined
        - aws_new_instance.elastic_ip is defined

    - name: "add {{ aws_new_instance.ipv6 }} to the new machine"
      ansible.builtin.command: >
        aws ec2 --profile {{ aws_new_instance.profile }} assign-ipv6-addresses
        --ipv6-addresses {{ aws_new_instance.ipv6 }}
        --network-interface-id {{ instances_started.instances[0].network_interfaces[0].network_interface_id }}
      when:
        - aws_new_instance.eni is not defined
        - aws_new_instance.ipv6 is defined

    - name: print ipv4
      debug:
        msg:
          - "Instance ID: {{ instances_started.instances[0].instance_id }}"
          - "Elastic IP: {{ aws_new_instance.elastic_ip }}"
