#!/usr/bin/env bash

while :
do
  PGPASSWORD=password pg_isready -d test_db -U user -h localhost -p 5432 && \
  PGPASSWORD=password psql -d test_db -U user -h localhost -p 5432 -c "SELECT 1" > /dev/null 2>&1 && \
  break
  sleep 1
done
