---
name: Move new issues to issues review

on:
  issues:
    types: [opened]
permissions:
  repository-projects: write
  pull-requests: read
  issues: read
jobs:
  move-new-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # v0.5.0
        with:
          project-url: https://github.com/orgs/fedora-copr/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
