name: Run Pytest
on:
  push:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      - name: Install tox
        run: pip install tox
      - name: Run pytest for base package
        run: tox -e pytest_base
      - name: Run pytest for server
        run: tox -e pytest_server
