---
name: Lint Python issues

on:
  push:
  pull_request:
    branches: [main]

jobs:
  python-lint-job:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0

      - name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@3fe529c95a55cf7d25d1ef73d53f790710c9a352 # v1.10.0
        id: VCS_Diff_Lint
        with:
          install_rpm_packages: |
            python3-numpy
            python3-pytest
            python3-fastapi
            python3-gitlab
            python3-sqlalchemy
            python3-flexmock
            python3-alembic
          linter_tags: |
            pylint
            ruff

      - name: Upload artifact with detected defects in SARIF format
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: VCS Diff Lint SARIF
          path: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

      - name: Upload SARIF to GitHub using github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@fca7ace96b7d713c7035871441bd52efbe39e27e # v3.28.19
        with:
          sarif_file: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}
